import type { LanguageOption } from "#/features/flashcards/model/types";

export const LANGUAGE_OPTIONS: LanguageOption[] = [
	{
		id: "georgian",
		label: "Georgian",
		nativeLabel: "Kartuli",
		emoji: "🇬🇪",
		description: "Daily Georgian vocabulary with clear Latin transliteration.",
		promptLabel: "Georgian word or phrase",
		promptPlaceholder: "e.g. madloba",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. thank you",
		examplePlaceholder: "e.g. Dakhmarebistvis didi madloba.",
		notePlaceholder: "Sound clue, case reminder, or memory hook",
		pronunciationLabel: "Transliteration / pronunciation",
		pronunciationPlaceholder: "madloba",
		starterNudge: "A small daily-phrase starter deck works well here.",
		palette: {
			primary: "#8ed8ff",
			secondary: "#ff9d7c",
			accent: "#ffe17d",
			glow: "rgba(142, 216, 255, 0.32)",
		},
	},
	{
		id: "japanese",
		label: "Japanese",
		nativeLabel: "日本語",
		emoji: "🇯🇵",
		description: "Particles, rhythm, and compact phrases for daily life.",
		promptLabel: "Japanese word or phrase",
		promptPlaceholder: "e.g. いただきます",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. Thanks for the meal",
		examplePlaceholder: "e.g. 食べる前に「いただきます」と言います。",
		notePlaceholder: "Sound cues, etiquette, or a quick memory hook",
		pronunciationLabel: "Reading / pronunciation",
		pronunciationPlaceholder: "itadakimasu",
		starterNudge: "A tiny travel-and-everyday starter deck works well here.",
		palette: {
			primary: "#7ce7da",
			secondary: "#ff8eb3",
			accent: "#ffd76e",
			glow: "rgba(124, 231, 218, 0.34)",
		},
	},
	{
		id: "spanish",
		label: "Spanish",
		nativeLabel: "Español",
		emoji: "🇪🇸",
		description: "Conversational phrases, clean pronunciation, fast momentum.",
		promptLabel: "Spanish word or phrase",
		promptPlaceholder: "e.g. me da igual",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. I don't mind",
		examplePlaceholder: "e.g. Si quieres sushi o pizza, me da igual.",
		notePlaceholder: "Tone, register, or a mnemonic for tricky words",
		pronunciationLabel: "Pronunciation note",
		pronunciationPlaceholder: "meh dah ee-GWAL",
		starterNudge: "Starter cards can focus on food, travel, and quick replies.",
		palette: {
			primary: "#ffab70",
			secondary: "#ff7d97",
			accent: "#ffe07a",
			glow: "rgba(255, 171, 112, 0.34)",
		},
	},
	{
		id: "french",
		label: "French",
		nativeLabel: "Français",
		emoji: "🇫🇷",
		description: "Elegant phrases with an ear for liaison and tone.",
		promptLabel: "French word or phrase",
		promptPlaceholder: "e.g. ça marche",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. that works / sounds good",
		examplePlaceholder: "e.g. On se retrouve à huit heures ? Ça marche.",
		notePlaceholder: "Grammar shortcut, register, or sound reminder",
		pronunciationLabel: "Pronunciation note",
		pronunciationPlaceholder: "sah marsh",
		starterNudge:
			"Starter cards shine when they mix polite and casual phrases.",
		palette: {
			primary: "#86c5ff",
			secondary: "#ff8ea6",
			accent: "#ffd97c",
			glow: "rgba(134, 197, 255, 0.34)",
		},
	},
	{
		id: "korean",
		label: "Korean",
		nativeLabel: "한국어",
		emoji: "🇰🇷",
		description: "Useful everyday Korean with polite endings and sound cues.",
		promptLabel: "Korean word or phrase",
		promptPlaceholder: "e.g. 괜찮아요",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. It's okay / no thanks",
		examplePlaceholder: "e.g. 물은 괜찮아요. 커피 주세요.",
		notePlaceholder: "Honorific context or a quick pronunciation clue",
		pronunciationLabel: "Romanization / pronunciation",
		pronunciationPlaceholder: "gwaen-cha-na-yo",
		starterNudge:
			"Starter cards should balance polite endings and daily nouns.",
		palette: {
			primary: "#8ed8ff",
			secondary: "#c796ff",
			accent: "#ffe27b",
			glow: "rgba(142, 216, 255, 0.34)",
		},
	},
	{
		id: "german",
		label: "German",
		nativeLabel: "Deutsch",
		emoji: "🇩🇪",
		description:
			"Crisp utility phrases with strong compound-word memory hooks.",
		promptLabel: "German word or phrase",
		promptPlaceholder: "e.g. auf jeden Fall",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. definitely",
		examplePlaceholder: "e.g. Auf jeden Fall komme ich morgen vorbei.",
		notePlaceholder: "Case reminder, word order trick, or mnemonic",
		pronunciationLabel: "Pronunciation note",
		pronunciationPlaceholder: "owf YAY-den fall",
		starterNudge:
			"A starter set of daily replies and movement verbs feels useful fast.",
		palette: {
			primary: "#f6c66a",
			secondary: "#ff8d74",
			accent: "#9fcd7d",
			glow: "rgba(246, 198, 106, 0.3)",
		},
	},
	{
		id: "italian",
		label: "Italian",
		nativeLabel: "Italiano",
		emoji: "🇮🇹",
		description: "Warm, musical vocabulary for social and travel situations.",
		promptLabel: "Italian word or phrase",
		promptPlaceholder: "e.g. ci penso io",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. I'll take care of it",
		examplePlaceholder: "e.g. Non preoccuparti, ci penso io.",
		notePlaceholder: "Gesture, context, or memory hook",
		pronunciationLabel: "Pronunciation note",
		pronunciationPlaceholder: "chee PEN-so ee-oh",
		starterNudge: "Starter cards should lean social, useful, and expressive.",
		palette: {
			primary: "#8ceea8",
			secondary: "#ff957a",
			accent: "#fff080",
			glow: "rgba(140, 238, 168, 0.32)",
		},
	},
	{
		id: "portuguese",
		label: "Portuguese",
		nativeLabel: "Português",
		emoji: "🇵🇹",
		description: "Travel-ready phrases with warm cadence and quick utility.",
		promptLabel: "Portuguese word or phrase",
		promptPlaceholder: "e.g. tudo bem",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. all good",
		examplePlaceholder: "e.g. Oi, tudo bem?",
		notePlaceholder: "Sound cue, usage note, or memory hook",
		pronunciationLabel: "Pronunciation",
		pronunciationPlaceholder: "too-doo beng",
		starterNudge:
			"Starter cards work best with daily replies and courtesy phrases.",
		palette: {
			primary: "#7be0b8",
			secondary: "#ffd06a",
			accent: "#8ed8ff",
			glow: "rgba(123, 224, 184, 0.32)",
		},
	},
	{
		id: "arabic",
		label: "Arabic",
		nativeLabel: "العربية",
		emoji: "🇸🇦",
		description: "High-value phrases with script, sound, and greeting rhythm.",
		promptLabel: "Arabic word or phrase",
		promptPlaceholder: "e.g. شكراً",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. thank you",
		examplePlaceholder: "e.g. شكراً على مساعدتك.",
		notePlaceholder: "Root, register, or memory clue",
		pronunciationLabel: "Transliteration / pronunciation",
		pronunciationPlaceholder: "shukran",
		starterNudge:
			"Starter cards should focus on greetings and practical repair phrases.",
		palette: {
			primary: "#ffd06a",
			secondary: "#8ed8ff",
			accent: "#6ee7b7",
			glow: "rgba(255, 208, 106, 0.3)",
		},
	},
	{
		id: "turkish",
		label: "Turkish",
		nativeLabel: "Türkçe",
		emoji: "🇹🇷",
		description:
			"Friendly, everyday phrases with clear agglutinative patterns.",
		promptLabel: "Turkish word or phrase",
		promptPlaceholder: "e.g. teşekkürler",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. thanks",
		examplePlaceholder: "e.g. Yardımın için teşekkürler.",
		notePlaceholder: "Suffix clue or memory hook",
		pronunciationLabel: "Pronunciation",
		pronunciationPlaceholder: "te-sheh-kur-ler",
		starterNudge:
			"Starter cards should mix greetings, requests, and common verbs.",
		palette: {
			primary: "#ff9c87",
			secondary: "#ffd06a",
			accent: "#6ee7b7",
			glow: "rgba(255, 156, 135, 0.32)",
		},
	},
	{
		id: "russian",
		label: "Russian",
		nativeLabel: "Русский",
		emoji: "🇷🇺",
		description:
			"Core spoken vocabulary with script support and quick daily use.",
		promptLabel: "Russian word or phrase",
		promptPlaceholder: "e.g. спасибо",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. thank you",
		examplePlaceholder: "e.g. Спасибо за помощь.",
		notePlaceholder: "Stress pattern or mnemonic",
		pronunciationLabel: "Transliteration / pronunciation",
		pronunciationPlaceholder: "spa-SEE-ba",
		starterNudge:
			"Starter cards should include etiquette, directions, and repair phrases.",
		palette: {
			primary: "#8ed8ff",
			secondary: "#ff8ea6",
			accent: "#ffd06a",
			glow: "rgba(142, 216, 255, 0.32)",
		},
	},
	{
		id: "mandarin",
		label: "Mandarin",
		nativeLabel: "中文",
		emoji: "🇨🇳",
		description:
			"Useful everyday Mandarin with pinyin support and compact phrases.",
		promptLabel: "Mandarin word or phrase",
		promptPlaceholder: "e.g. 谢谢",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. thank you",
		examplePlaceholder: "e.g. 谢谢你的帮助。",
		notePlaceholder: "Tone clue or memory hook",
		pronunciationLabel: "Pinyin / pronunciation",
		pronunciationPlaceholder: "xie xie",
		starterNudge:
			"Starter cards should lean into common verbs, courtesy, and repair phrases.",
		palette: {
			primary: "#ffd06a",
			secondary: "#ff9c87",
			accent: "#8ed8ff",
			glow: "rgba(255, 208, 106, 0.32)",
		},
	},
	{
		id: "dutch",
		label: "Dutch",
		nativeLabel: "Nederlands",
		emoji: "🇳🇱",
		description: "Compact everyday phrases with clean pronunciation notes.",
		promptLabel: "Dutch word or phrase",
		promptPlaceholder: "e.g. geen probleem",
		translationLabel: "English translation",
		translationPlaceholder: "e.g. no problem",
		examplePlaceholder: "e.g. Geen probleem, ik help wel.",
		notePlaceholder: "Sound cue or usage reminder",
		pronunciationLabel: "Pronunciation",
		pronunciationPlaceholder: "khayn pro-BLAYM",
		starterNudge:
			"Starter cards work well when they focus on direct, high-frequency replies.",
		palette: {
			primary: "#8ed8ff",
			secondary: "#ffd06a",
			accent: "#ff9c87",
			glow: "rgba(142, 216, 255, 0.32)",
		},
	},
];

export const DEFAULT_NATIVE_LANGUAGE_ID = "english";

export const NATIVE_LANGUAGE_OPTIONS = [
	{ id: "english", label: "English" },
	{ id: "spanish", label: "Spanish" },
	{ id: "french", label: "French" },
	{ id: "german", label: "German" },
	{ id: "italian", label: "Italian" },
	{ id: "portuguese", label: "Portuguese" },
	{ id: "japanese", label: "Japanese" },
	{ id: "korean", label: "Korean" },
	{ id: "russian", label: "Russian" },
	{ id: "turkish", label: "Turkish" },
] as const;

export function getLanguageOption(languageId: string | null | undefined) {
	return (
		LANGUAGE_OPTIONS.find((language) => language.id === languageId) ?? null
	);
}

export function getNativeLanguageLabel(languageId: string) {
	return (
		NATIVE_LANGUAGE_OPTIONS.find((language) => language.id === languageId)
			?.label ?? "English"
	);
}
